#!/bin/env python3
header = open("embed.h", "w")
source = open("embed.c", "w")

warning = "// Generated by assets/include.py during the build process. Do not edit this file by hand.\n"
header.write("#pragma once\n\n" + warning + "#include <stddef.h>\n")
source.write(warning + "#include <stddef.h>\n")

files_to_embed = [("Amiko-Regular.ttf", "font_data")]

for e in files_to_embed:
	with open(e[0], "rb") as f:
		data = f.read()

	header.write(f"\nextern unsigned char const {e[1]}[];\n")
	header.write(f"extern size_t const {e[1] + '_len'};\n")

	source.write(f"\nsize_t const {e[1] + '_len'} = {len(data)};\n")
	source.write(f"\nunsigned char const {e[1]}[] = " + "{")
	for index, b in enumerate(data):
		b = "0x" + format(b, "02x")
		if (index % 12 == 0):
			source.write("\n\t" + b + ",")
		else:
			source.write(" " + b + ",")
	source.write("\n};\n")
